# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Maxim Si
"""Схема слоёв, групп и полей стиля для панели настроек (Effect Controls).

Дерево «слой → группа → поле». Единственный источник дефолтов — core.styles.BASE.
"""
import copy
from core import styles

LAYERS = [
    {
        "id": "comp",
        "label": "Композиция",
        "toggle": None,
        "items": [
            {
                "type": "group",
                "id": "comp.order",
                "label": "Порядок слоёв",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "layer_order",
                        "label": "Порядок слоёв",
                        "tip": "Порядок наложения слоёв: выше в списке — выше в кадре (перекрывает всё, что ниже). Перетаскивай строки мышью или двигай стрелками.",
                        "ctl": "layer_order",
                    },
                ],
            },
            {
                "type": "group",
                "id": "comp.blur",
                "label": "Размытие на старте",
                "fx": True,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "start_blur",
                        "label": "Сила размытия, px",
                        "tip": "В разобранном проекте это делается руками в каждом ролике: Adjustment Layer с Gaussian Blur, размытие на старте (px). В стиле хранится в px.",
                        "ctl": "num",
                        "min": 0,
                        "max": 100,
                        "lim_min": 0,
                        "lim_max": 200,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "start_blur_dur",
                        "label": "Уходит в ноль за, с",
                        "tip": "За сколько секунд стартовое размытие уходит в ноль.",
                        "ctl": "num",
                        "positive": True,
                        "min": 0,
                        "max": 3,
                        "lim_min": 0,
                        "lim_max": 10,
                        "step": 0.01,
                    },
                ],
            },
        ],
    },
    {
        "id": "subs",
        "label": "Субтитры",
        "toggle": None,
        "items": [
            {
                "type": "group",
                "id": "subs.text",
                "label": "Текст",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "font",
                        "label": "Шрифт обычный",
                        "tip": None,
                        "ctl": "font",
                        "list": "fontlist",
                        "placeholder": "SFPro-CondensedSemibold",
                    },
                    {
                        "type": "field",
                        "key": "sub_case",
                        "label": "Регистр",
                        "tip": "Как писать субтитры: КАПСОМ (как сегодня), строчными или «Как в предложении» (первое слово реплики с заглавной).",
                        "ctl": "select",
                        "options": [
                            ["upper", "КАПСОМ"],
                            ["lower", "строчными"],
                            ["sentence", "Как в предложении"],
                        ],
                    },
                    {
                        "type": "field",
                        "key": "sub_fill",
                        "label": "Цвет субтитров",
                        "tip": None,
                        "ctl": "color",
                    },
                    {
                        "type": "field",
                        "key": "sub_words_per_row",
                        "label": "Слов в строке",
                        "tip": "Сколько слов группировать в одну строку (1 = по одному слову, как раньше).",
                        "ctl": "int",
                        "positive": True,
                        "min": 1,
                        "max": 6,
                    },
                    {
                        "type": "field",
                        "key": "sub_rows_max",
                        "label": "Строк",
                        "tip": "Максимум строк при переносе: 1 (ужимать шрифт по ширине) или 2 (разбивать на две строки).",
                        "ctl": "int",
                        "positive": True,
                        "min": 1,
                        "max": 2,
                    },
                    {
                        "type": "group",
                        "id": "subs.hl",
                        "label": "Выделение",
                        "fx": False,
                        "toggle": None,
                        "items": [
                            {
                                "type": "field",
                                "key": "hl_fill",
                                "label": "Цвет выделения",
                                "tip": None,
                                "ctl": "color",
                            },
                            {
                                "type": "field",
                                "key": "hl_bold",
                                "label": "Выделять жирным",
                                "tip": None,
                                "ctl": "bool",
                            },
                            {
                                "type": "field",
                                "key": "hl_row_anim",
                                "label": "Жёлтые в строке",
                                "tip": "только когда в строке больше одного слова. Когда произнесено — "
                                       "белые слова появляются со строкой, жёлтое въезжает в момент, "
                                       "когда его говорят (до этого место под ним пустое). Вместе со "
                                       "строкой — жёлтое въезжает сразу со строкой",
                                "ctl": "select",
                                "options": [["word", "когда произнесено"], ["row", "вместе со строкой"]],
                            },
                            {
                                "type": "field",
                                "key": "hl_row_stack",
                                "label": "жёлтые подряд — стопкой",
                                "tip": "при нескольких словах в строке серия из двух и больше жёлтых подряд выходит из строк и складывается стопкой по одному слову, как в режиме «по слову»",
                                "ctl": "bool",
                            },
                            {
                                "type": "field",
                                "key": "hl_blur",
                                "label": "блюр появления",
                                "tip": "жёлтое слово появляется из размытия (Gaussian Blur) — "
                                       "на тех же ключах, что подъём",
                                "ctl": "bool",
                            },
                            {
                                "type": "field",
                                "key": "hl_blur_amt",
                                "label": "Сила блюра",
                                "tip": None,
                                "ctl": "num",
                                "min": 0,
                                "max": 200,
                                "lim_min": 0,
                                "lim_max": 500,
                                "step": 0.1,
                                "show_if": {"key": "hl_blur", "eq": True},
                            },
                            {
                                "type": "field",
                                "key": "hl_font",
                                "label": "Шрифт выделения",
                                "tip": None,
                                "ctl": "font",
                                "list": "hlfontlist",
                                "nullable": True,
                                "show_if": {"key": "hl_bold", "eq": True},
                                "placeholder": "пусто = авто-жирный",
                            },
                        ],
                    },
                ],
            },
            {
                "type": "group",
                "id": "subs.tr",
                "label": "Transform",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "sub_y",
                        "label": "Высота субтитров, % снизу",
                        "tip": "Насколько высоко от низа кадра стоит строка субтитров. Дефолт — 40%.",
                        "ctl": "num",
                        "conv": "inv_pct",
                        "min": 0,
                        "max": 90,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "sub_scale",
                        "label": "Масштаб субтитров, %",
                        "tip": "Масштаб слоя прекомпа субтитров (как ручной Scale в AE): раскладка — перенос строк, автоподжатие, шаг стопки — не меняется, уменьшается готовый слой. Дефолт 100%.",
                        "ctl": "num",
                        "positive": True,
                        "min": 20,
                        "max": 200,
                        "step": 1,
                    },
                ],
            },
            {
                "type": "group",
                "id": "subs.timing",
                "label": "Тайминг",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "insert_sub_swap",
                        "label": "Субтитры уходят на время фото",
                        "tip": "Работает только при анимации «выезд снизу»; субтитры и плашка исчезают, пока фото кам2 на экране",
                        "ctl": "bool",
                    },
                ],
            },
            {
                "type": "group",
                "id": "subs.bg",
                "label": "Фон субтитров",
                "fx": False,
                "toggle": "sub_bg",
                "items": [
                    {
                        "type": "field",
                        "key": "sub_bg_fill",
                        "label": "Цвет фона",
                        "tip": "Цвет плашки под субтитрами.",
                        "ctl": "color",
                    },
                    {
                        "type": "field",
                        "key": "sub_bg_op",
                        "label": "Прозрачность фона, %",
                        "tip": "Прозрачность плашки (Opacity), %. Дефолт — 72%.",
                        "ctl": "num",
                        "min": 0,
                        "max": 100,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "sub_bg_h",
                        "label": "Высота фона, px",
                        "tip": "Высота плашки в пикселях композиции (дефолт 160 px).",
                        "ctl": "num",
                        "min": 40,
                        "max": 400,
                        "lim_min": 20,
                        "lim_max": 500,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "sub_bg_round",
                        "label": "Скругление фона, px",
                        "tip": "Радиус скругления углов плашки (дефолт 78 px).",
                        "ctl": "num",
                        "min": 0,
                        "max": 200,
                        "lim_min": 0,
                        "lim_max": 250,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "sub_bg_pad",
                        "label": "Поля фона, %",
                        "tip": "Отступ плашки по бокам от текста строки, % от ширины строки (дефолт 18%).",
                        "ctl": "num",
                        "min": 0,
                        "max": 50,
                        "lim_min": 0,
                        "lim_max": 100,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "sub_bg_padmin",
                        "label": "Минимальное поле, px",
                        "tip": "Минимальное поле плашки по бокам от текста в пикселях (дефолт 70 px). Проценты — от ширины строки, но меньше этого значения поле не бывает.",
                        "ctl": "num",
                        "min": 0,
                        "max": 200,
                        "lim_min": 0,
                        "lim_max": 400,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "sub_bg_dy",
                        "label": "Сдвиг фона Y, px",
                        "tip": "Доводка по вертикали, + вниз (дефолт 0 px).",
                        "ctl": "num",
                        "min": -150,
                        "max": 150,
                        "lim_min": -300,
                        "lim_max": 300,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "sub_bg_anim",
                        "label": "Плашка переезжает за, с",
                        "tip": "За сколько секунд плашка переезжает на новую ширину, когда меняется строка (дефолт 0.22 с).",
                        "ctl": "num",
                        "min": 0,
                        "max": 2,
                        "lim_min": 0,
                        "lim_max": 5,
                        "step": 0.01,
                    },
                ],
            },
        ],
    },
    {
        "id": "intro",
        "label": "Интро",
        "toggle": None,
        "items": [
            {
                "type": "group",
                "id": "intro.text",
                "label": "Текст",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "intro_font",
                        "label": "Шрифт интро",
                        "tip": None,
                        "ctl": "font",
                        "list": "fontlist",
                        "nullable": True,
                        "placeholder": "как у субтитров",
                    },
                    {
                        "type": "field",
                        "key": "intro_hl_font",
                        "label": "Шрифт выделения интро",
                        "tip": None,
                        "ctl": "font",
                        "list": "fontlist",
                        "nullable": True,
                        "placeholder": "как выделение",
                    },
                    {
                        "type": "field",
                        "key": "intro_fill",
                        "label": "Цвет текста интро",
                        "tip": "Цвет обычного (не выделенного) текста интро-вставок. Пусто = белый (как сегодня).",
                        "ctl": "color_opt",
                        "placeholder": "пусто = белый",
                    },
                    {
                        "type": "field",
                        "key": "intro_hl_fill",
                        "label": "Цвет выделения интро",
                        "tip": "Цвет выделенного (жёлтого) текста интро-вставок. Пусто = как обычное выделение (Цвет выделения выше).",
                        "ctl": "color_opt",
                        "placeholder": "пусто = как выделение",
                    },
                    {
                        "type": "field",
                        "key": "hl_fill3",
                        "label": "3-й цвет выделения",
                        "tip": "Цвет строки интро с color=\"accent\" — третий, отдельный от обычного жёлтого выделения.",
                        "ctl": "color",
                    },
                    {
                        "type": "group",
                        "id": "intro.accent",
                        "label": "Акцент",
                        "fx": False,
                        "toggle": None,
                        "items": [
                            {
                                "type": "field",
                                "key": "accent_font",
                                "label": "Акцентный шрифт",
                                "tip": "Шрифт отдельных слов интро (акцент, задание R): строка с галкой акцента ставится этим шрифтом и другим регистром. Пусто = акцент выключен. В превью ищется по имени семейства, в AE ставится PostScript-имя.",
                                "ctl": "font",
                                "list": "fontlist",
                                "nullable": True,
                                "placeholder": "пусто = выкл",
                            },
                            {
                                "type": "field",
                                "key": "accent_case",
                                "label": "Регистр акцента",
                                "tip": None,
                                "ctl": "select",
                                "options": [
                                    ["title", "Заглавная первая"],
                                    ["as-is", "Как есть"],
                                    ["upper", "Все заглавные"],
                                ],
                            },
                        ],
                    },
                    {
                        "type": "group",
                        "id": "intro.back",
                        "label": "Задний план",
                        "fx": False,
                        "toggle": None,
                        "items": [
                            {
                                "type": "field",
                                "key": "back_font",
                                "label": "Шрифт заднего плана",
                                "tip": "Шрифт строк интро на «заднем плане»: если в прекомпе есть глитч, соседние строки уходят на задний план этим шрифтом и регистром back_case. Пусто = выключено. В превью ищется по имени семейства, в AE ставится PostScript-имя.",
                                "ctl": "font",
                                "list": "fontlist",
                                "nullable": True,
                                "placeholder": "пусто = выкл",
                            },
                            {
                                "type": "field",
                                "key": "back_case",
                                "label": "Регистр заднего плана",
                                "tip": None,
                                "ctl": "select",
                                "options": [
                                    ["lower", "Все строчные"],
                                    ["as-is", "Как есть"],
                                    ["upper", "Все заглавные"],
                                ],
                            },
                            {
                                "type": "field",
                                "key": "back_scale",
                                "label": "Масштаб заднего плана",
                                "tip": "Масштаб шрифта строк заднего плана, доля от FONT_SIZE (дефолт 0.69).",
                                "ctl": "num",
                                "min": 0.2,
                                "max": 2,
                                "lim_min": 0.2,
                                "lim_max": 5,
                                "step": 0.01,
                            },
                            {
                                "type": "field",
                                "key": "back_step",
                                "label": "Межстрочный заднего плана сверху, %",
                                "tip": "шаг от строки выше до строки заднего плана (и между строками заднего плана), % от межстрочного интервала интро",
                                "ctl": "num",
                                "min": 10,
                                "max": 300,
                                "lim_min": 10,
                                "lim_max": 300,
                                "step": 1,
                                "conv": "frac_pct_int",
                            },
                            {
                                "type": "field",
                                "key": "back_step_after",
                                "label": "Межстрочный заднего плана снизу, %",
                                "tip": "шаг от строки заднего плана до обычной строки под ней, % от межстрочного интервала интро",
                                "ctl": "num",
                                "min": 10,
                                "max": 300,
                                "lim_min": 10,
                                "lim_max": 300,
                                "step": 1,
                                "conv": "frac_pct_int",
                                # Ключа в стиле нет — значение берётся у парной ручки
                                # back_step (задание ZZ): так же считает и сборка, поэтому
                                # панель показывает его же число, а не ноль.
                                "nullable": True,
                                "fallback_key": "back_step",
                            },
                            {
                                "type": "group",
                                "id": "intro.back.shadow",
                                "label": "Тень заднего плана",
                                "fx": True,
                                "toggle": None,
                                "items": [
                                    {
                                        "type": "field",
                                        "key": "back_shadow_op",
                                        "label": "Тень заднего плана, прозрачность",
                                        "tip": "Прозрачность (Opacity) тени строк заднего плана, 0..255. Дефолт 131.",
                                        "ctl": "num",
                                        "min": 0,
                                        "max": 255,
                                        "step": 1,
                                    },
                                    {
                                        "type": "field",
                                        "key": "back_shadow_soft",
                                        "label": "Тень заднего плана, мягкость, px",
                                        "tip": "Мягкость (Softness) тени строк заднего плана, px. Дефолт 38.",
                                        "ctl": "num",
                                        "min": 0,
                                        "max": 100,
                                        "lim_min": 0,
                                        "lim_max": 500,
                                        "step": 0.1,
                                    },
                                ],
                            },
                        ],
                    },
                ],
            },
            {
                "type": "group",
                "id": "intro.tr",
                "label": "Transform",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "intro_scale",
                        "label": "Масштаб интро, %",
                        "tip": "Общий размер ВСЕГО интро, % — висит на нуле «интро». Интро привязано к нулу Камеры 1 и наследует её зум: врезался в кадр — интро выросло вместе с ним, этим приводишь обратно. Автоподжатие длинных строк работает как раньше, поверх.",
                        "ctl": "num",
                        "positive": True,
                        "min": 10,
                        "max": 300,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "intro_line_step",
                        "label": "Межстрочный интервал, %",
                        "tip": "расстояние между строками интро, % от обычного (100 = как было). Межстрочный заднего плана считается от него же",
                        "ctl": "num",
                        "min": 50,
                        "max": 250,
                        "lim_min": 20,
                        "lim_max": 400,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "intro_big_gap",
                        "label": "Зазор до большого слова, px",
                        "tip": "расстояние между большим словом слева и стопкой строк справа",
                        "ctl": "num",
                        "min": 0,
                        "max": 400,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "intro_big_step",
                        "label": "Межстрочный стопки, %",
                        "tip": "шаг строк справа от большого слова, % от обычного шага интро (160 px); не зависит от общего межстрочного",
                        "ctl": "num",
                        "min": 30,
                        "max": 200,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "intro_big_over",
                        "label": "Большое выше стопки, %",
                        "tip": "высота большого слова в % от высоты стопки (от верха заглавных первой строки до базовой линии последней)",
                        "ctl": "num",
                        "min": 80,
                        "max": 160,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "intro_x",
                        "label": "Интро по горизонтали",
                        "tip": "Общий сдвиг ВСЕГО интро по горизонтали, + вправо (% ширины кадра). Пара к «Интро по вертикали»; в стиле хранится px, ползунок показывает долю кадра.",
                        "ctl": "num",
                        "conv": "pct_fx",
                        "min": -50,
                        "max": 100,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "intro_cam",
                        "label": "интро едет с камерой",
                        "tip": "включено — интро привязано к нулу Камеры 1 (зум, сдвиг, слежение); выключено — стоит на месте в кадре",
                        "ctl": "bool",
                    },
                ],
            },
            {
                "type": "group",
                "id": "intro.cam1",
                "label": "Камера 1",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "intro_y",
                        "label": "Интро по вертикали",
                        "tip": "Общий сдвиг ВСЕГО интро по вертикали, + вниз (% кадра). Двигает все прекомпы разом — то, что раньше приходилось таскать в AE руками. В стиле по-прежнему хранится px, ползунок показывает долю кадра.",
                        "ctl": "num",
                        "conv": "pct_h",
                        "min": -50,
                        "max": 100,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "intro_anchor",
                        "label": "Якорь интро, камера 1",
                        "tip": "За что держится блок интро на камере 1. «По центру» — как раньше: блок центрируется по числу строк, и добавленная строка поднимает первую. «На первой строке» — первая строка стоит на месте, добавленные ложатся ниже (удобно, когда строку дописали, а верх блока трогать нельзя).",
                        "ctl": "select",
                        "options": [
                            ["center", "По центру"],
                            ["first", "На первой строке"],
                        ],
                    },
                ],
            },
            {
                "type": "group",
                "id": "intro.cam2",
                "label": "Камера 2",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "intro_y2",
                        "label": "Интро на кам2 Y",
                        "tip": "Добавка к сдвигу для интро, которое появляется на перебивке: такие прекомпы висят на отдельном нуле «интро на кам2». На перебивке кадр другой, и текст за спиной обычно ставят ниже — здесь это делается разом и переживает пересборку.",
                        "ctl": "num",
                        "conv": "pct_h",
                        "min": -50,
                        "max": 100,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "intro_anchor2",
                        "label": "Якорь интро, камера 2",
                        "tip": "То же для групп интро, попавших на перебивку (они висят на своём нуле «интро на кам2»): на кадре перебивки блок обычно держат иначе, чем на камере 1.",
                        "ctl": "select",
                        "options": [
                            ["center", "По центру"],
                            ["first", "На первой строке"],
                        ],
                    },
                ],
            },
            {
                "type": "group",
                "id": "intro.glow",
                "label": "Glow",
                "fx": True,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "intro_glow",
                        "label": "Glow интро",
                        "tip": "Интенсивность свечения (Glow Intensity) текста интро-вставок. AE-дефолт 1.0; больше = ярче свечение.",
                        "ctl": "num",
                        "min": 0,
                        "max": 5,
                        "lim_min": 0,
                        "lim_max": 10,
                        "step": 0.1,
                    },
                ],
            },
            {
                "type": "group",
                "id": "intro.shadow",
                "label": "Тень слов",
                "fx": True,
                "toggle": "intro_shadow",
                "items": [
                    {
                        "type": "field",
                        "key": "intro_shadow_op",
                        "label": "Тень интро, прозрачность",
                        "tip": "Прозрачность (Opacity) тени слов интро, 0..255. Дефолт 116.",
                        "ctl": "num",
                        "min": 0,
                        "max": 255,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "intro_shadow_dir",
                        "label": "Тень интро, направление°",
                        "tip": "Направление тени слов интро, градусы. Дефолт 16.",
                        "ctl": "angle",
                        "min": 0,
                        "max": 360,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "intro_shadow_dist",
                        "label": "Тень интро, дистанция, px",
                        "tip": "Дистанция тени слов интро, px. Дефолт 6.8.",
                        "ctl": "num",
                        "min": 0,
                        "max": 100,
                        "lim_min": 0,
                        "lim_max": 500,
                        "step": 0.1,
                    },
                    {
                        "type": "field",
                        "key": "intro_shadow_soft",
                        "label": "Тень интро, мягкость, px",
                        "tip": "Мягкость (Softness) тени слов интро, px. Дефолт 34.",
                        "ctl": "num",
                        "min": 0,
                        "max": 100,
                        "lim_min": 0,
                        "lim_max": 500,
                        "step": 0.1,
                    },
                ],
            },
            {
                "type": "group",
                "id": "intro.cshadow",
                "label": "Тень прекомпа",
                "fx": True,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "intro_comp_shadow_fill",
                        "label": "Тень интро, камера 1",
                        "tip": "Цвет тени ПРЕКОМПА интро, который висит на нуле камеры 1. Дефолт — белая, как ставил шаблон (dropShadow 68).",
                        "ctl": "color",
                    },
                    {
                        "type": "field",
                        "key": "intro_comp_shadow_op",
                        "label": "Тень интро, камера 1, прозрачность",
                        "tip": "Непрозрачность (Opacity) тени прекомпа интро на камере 1, 0..255. Дефолт 68.",
                        "ctl": "num",
                        "min": 0,
                        "max": 255,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "intro_comp_shadow2_fill",
                        "label": "Тень интро, камера 2",
                        "tip": "Цвет тени ПРЕКОМПА интро, который висит на нуле «интро на кам2» (группа на перебивке). Дефолт — белая, как ставил шаблон (dropShadow 68).",
                        "ctl": "color",
                    },
                    {
                        "type": "field",
                        "key": "intro_comp_shadow2_op",
                        "label": "Тень интро, камера 2, прозрачность",
                        "tip": "Непрозрачность (Opacity) тени прекомпа интро на камере 2, 0..255. Дефолт 68.",
                        "ctl": "num",
                        "min": 0,
                        "max": 255,
                        "step": 1,
                    },
                ],
            },
            {
                "type": "group",
                "id": "intro.timing",
                "label": "Тайминг",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "intro_fade",
                        "label": "Фейд-аут интро, с",
                        "tip": "Длительность исчезновения каждого блока интро, у обычных и глитч-прекомпов; у обычных момент исчезновения не меняется — фейд начинается позже.",
                        "ctl": "num",
                        "min": 0.1,
                        "max": 0.75,
                        "step": 0.05,
                    },
                    {
                        "type": "field",
                        "key": "intro_fx_hold_add",
                        "label": "Полка глитча, если следом долго нет интро +, с",
                        "tip": "Добавка к полке (времени на экране) прекомпа с глитчем, когда следующий прекомп далеко или его нет: блок дольше стоит до спада (дефолт +0.3 с).",
                        "ctl": "num",
                        "min": 0,
                        "max": 2,
                        "lim_min": 0,
                        "lim_max": 5,
                        "step": 0.05,
                    },
                ],
            },
            {
                "type": "group",
                "id": "intro.order",
                "label": "Порядок",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "intro_roto_by_pos",
                        "label": "Интро над рото в нижней половине (камера 1)",
                        "tip": "Группа интро на Камере 1, чей блок стоит в НИЖНЕЙ половине кадра (зона субтитров), встаёт сразу над рото; блок в верхней половине остаётся под ним. Группы на перебивке (камера 2) и на видеовставке не трогаются. Выключено — как раньше.",
                        "ctl": "bool",
                    },
                ],
            },
            {
                "type": "group",
                "id": "intro.shade",
                "label": "Затемнение под интро",
                "fx": False,
                "toggle": "intro_shade",
                "items": [
                    {
                        "type": "field",
                        "key": "intro_shade_op",
                        "label": "Непрозрачность затемнения, %",
                        "tip": "Непрозрачность слоя затемнения",
                        "ctl": "num",
                        "min": 0,
                        "max": 100,
                        "step": 1,
                    },
                ],
            },
        ],
    },
    {
        "id": "caption",
        "label": "Подпись",
        "toggle": "caption",
        "items": [
            {
                "type": "group",
                "id": "caption.text",
                "label": "Текст",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "caption_font",
                        "label": "Шрифт подписи",
                        "tip": "Шрифт текста подписи (PostScript-имя).",
                        "ctl": "font",
                        "list": "fontlist",
                        "placeholder": "SFPro-Bold",
                    },
                    {
                        "type": "field",
                        "key": "caption_size",
                        "label": "Кегль подписи, px",
                        "tip": "Кегль шрифта подписи в пикселях, как он виден в кадре (дефолт 26 px).",
                        "ctl": "num",
                        "min": 10,
                        "max": 150,
                        "lim_min": 8,
                        "lim_max": 200,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "caption_case",
                        "label": "Регистр подписи",
                        "tip": "Регистр текста подписи: ВСЕ ПРОПИСНЫЕ (дефолт) или как введено.",
                        "ctl": "select",
                        "options": [
                            ["upper", "ВСЕ ПРОПИСНЫЕ"],
                            ["as-is", "Как введено"],
                        ],
                    },
                    {
                        "type": "field",
                        "key": "caption_fill",
                        "label": "Цвет текста",
                        "tip": "Цвет текста подписи.",
                        "ctl": "color",
                    },
                ],
            },
            {
                "type": "group",
                "id": "caption.tr",
                "label": "Transform",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "caption_x",
                        "label": "Позиция X, px",
                        "tip": "Левый край блока подписи (дефолт 55 px — вровень с началом верхней строки): плашка начинается ровно на этой точке, текст стоит по её центру.",
                        "ctl": "num",
                        "min": 0,
                        "max": 1080,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "caption_y",
                        "label": "Позиция Y, px",
                        "tip": "Базовая линия текста подписи в кадре (дефолт 228 px).",
                        "ctl": "num",
                        "min": 0,
                        "max": 1920,
                        "step": 1,
                    },
                ],
            },
            {
                "type": "group",
                "id": "caption.bg",
                "label": "Плашка",
                "fx": False,
                "toggle": "caption_bg",
                "items": [
                    {
                        "type": "field",
                        "key": "caption_bg_fill",
                        "label": "Цвет плашки",
                        "tip": "Цвет фона плашки под подписью.",
                        "ctl": "color",
                    },
                    {
                        "type": "field",
                        "key": "caption_bg_op",
                        "label": "Прозрачность плашки, %",
                        "tip": "Прозрачность плашки (Opacity), %. Дефолт — 45%.",
                        "ctl": "num",
                        "min": 0,
                        "max": 100,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "caption_bg_round",
                        "label": "Скругление плашки, px",
                        "tip": "Радиус скругления углов плашки (дефолт 68 px).",
                        "ctl": "num",
                        "min": 0,
                        "max": 150,
                        "lim_min": 0,
                        "lim_max": 200,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "caption_kx",
                        "label": "Множитель ширины",
                        "tip": "Множитель ширины плашки от ширины текста подписи (дефолт 1.718 — как в разобранном проекте).",
                        "ctl": "num",
                        "min": 0.1,
                        "max": 4,
                        "step": 0.001,
                    },
                    {
                        "type": "field",
                        "key": "caption_ky",
                        "label": "Множитель высоты",
                        "tip": "Множитель высоты плашки от высоты текста подписи (дефолт 2.484 — как в разобранном проекте).",
                        "ctl": "num",
                        "min": 0.1,
                        "max": 5,
                        "step": 0.001,
                    },
                ],
            },
        ],
    },
    {
        "id": "topline",
        "label": "Верхняя строка",
        "toggle": "top_line",
        "items": [
            {
                "type": "group",
                "id": "topline.tr",
                "label": "Transform",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "top_line_y",
                        "label": "Высота строки Y, px",
                        "tip": "Высота верхней строки в кадре, px от верхнего края (дефолт 162 px).",
                        "ctl": "num",
                        "min": 0,
                        "max": 600,
                        "lim_min": 0,
                        "lim_max": 1000,
                        "step": 1,
                    },
                ],
            },
            {
                "type": "group",
                "id": "topline.shape",
                "label": "Контур",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "top_line_w",
                        "label": "Длина строки, px",
                        "tip": "Длина (ширина) верхней строки в пикселях (дефолт 969 px).",
                        "ctl": "num",
                        "min": 100,
                        "max": 1080,
                        "lim_min": 50,
                        "lim_max": 1080,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "top_line_th",
                        "label": "Толщина, px",
                        "tip": "Толщина линии строки (дефолт 12.5 px).",
                        "ctl": "num",
                        "min": 1,
                        "max": 60,
                        "lim_min": 1,
                        "lim_max": 100,
                        "step": 0.5,
                    },
                ],
            },
            {
                "type": "group",
                "id": "topline.grad",
                "label": "Градиент",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "top_line_from",
                        "label": "Цвет начала",
                        "tip": "Цвет старта градиента верхней строки.",
                        "ctl": "color",
                    },
                    {
                        "type": "field",
                        "key": "top_line_to",
                        "label": "Цвет конца",
                        "tip": "Цвет конца градиента верхней строки.",
                        "ctl": "color",
                    },
                ],
            },
            {
                "type": "group",
                "id": "topline.track",
                "label": "Дорожка",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "top_line_track_fill",
                        "label": "Цвет дорожки",
                        "tip": "Цвет нижней полосы (дорожки) верхней строки.",
                        "ctl": "color",
                    },
                    {
                        "type": "field",
                        "key": "top_line_track_op",
                        "label": "Прозрачность дорожки, %",
                        "tip": "Прозрачность нижней полосы (дорожки), % (дефолт 16%).",
                        "ctl": "num",
                        "min": 0,
                        "max": 100,
                        "step": 1,
                    },
                ],
            },
        ],
    },
    {
        "id": "disc",
        "label": "Дисклеймер",
        "toggle": "disclaimer",
        "toggle_kind": "disc",
        "items": [
            {
                "type": "field",
                "key": "disclaimer",
                "label": "Текст дисклеймера (пусто = дефолт)",
                "tip": None,
                "ctl": "textarea",
                "nullable": True,
                "placeholder": "МАТЕРИАЛ НОСИТ ОБРАЗОВАТЕЛЬНЫЙ ХАРАКТЕР…",
            },
            {
                "type": "field",
                "key": "disc_gap",
                "label": "Зазор строк дисклеймера, px",
                "tip": "Зазор между БУКВАМИ соседних строк дисклеймера, px. Пусто = интервал авто, как сегодня. Задано — шаг строк не меньше, чем «хвост вниз верхней строки + высота букв нижней + зазор»: высоту букв берут из файла шрифта, поэтому после смены шрифта строки дисклеймера не наезжают друг на друга (для Oswald-Bold это 0.8). Кегль дисклеймера сам ужимается под ширину кадра — длинная строка не вылезает за край, но и узкий шрифт дисклеймер не раздувает.",
                "ctl": "num",
                "nullable": True,
                "placeholder": "авто",
                "min": 0,
                "max": 100,
                "step": 0.1,
            },
            {
                "type": "field",
                "key": "disclaimer_end",
                "label": "Повторить в конце",
                "tip": "Копия дисклеймера в конце ролика: держится 1 с и гаснет за 0.35 с (как головной, просто со сдвигом). Композиция удлиняется на его длительность — иначе слой окажется за краем и его не видно.",
                "ctl": "bool",
            },
        ],
    },
    {
        "id": "cam1",
        "label": "Камера 1",
        "toggle": None,
        "items": [
            {
                "type": "group",
                "id": "cam1.tr",
                "label": "Transform",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "cam1_fit",
                        "label": "Заполнение кадра, %",
                        "tip": "Сколько кадра занимает видео Камеры 1 при зуме нула 100%. 100 = кадр заполнен ровно, 120 = врезка на 20%, 90 = картинка мельче кадра. Считается от реального разрешения исходника, поэтому число одно и то же для 4K и для 1080p — масштаб из Премьера для Камеры 1 больше не используется (он врёт, если файл пережали). Зум кам1 идёт поверх и умножается на это число: врезался вдвое — вдвое сильнее и ездит. Ротоскоп человека едет следом. Перебивки Камеры 2 не трогает. Общий множитель зума камеры 1: действует как зум нула — вместе с кадром растут вставки кам1 и интро, точка наезда неподвижна.",
                        "ctl": "num",
                        "positive": True,
                        "min": 10,
                        "max": 300,
                        "lim_min": 10,
                        "lim_max": 400,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "cam1_zoom_cx",
                        "key2": "cam1_zoom_cy",
                        "label": "Точка наезда…",
                        "tip": None,
                        "ctl": "point",
                    },
                    {
                        "type": "field",
                        "key": "cam1_pan_x",
                        "label": "Сдвиг кадра X, px",
                        "tip": "Двигает весь кадр камеры 1 (Position нула), точка наезда остаётся на месте; вставки кам1 и интро едут вместе с кадром.",
                        "ctl": "num",
                        "min": -500,
                        "max": 500,
                        "lim_min": -2000,
                        "lim_max": 2000,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "cam1_pan_y",
                        "label": "Сдвиг кадра Y, px",
                        "tip": "Двигает весь кадр камеры 1 (Position нула), точка наезда остаётся на месте; вставки кам1 и интро едут вместе с кадром.",
                        "ctl": "num",
                        "min": -500,
                        "max": 500,
                        "lim_min": -2000,
                        "lim_max": 2000,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "cam1_rot",
                        "label": "Горизонт, °",
                        "tip": "Поворачивает только кадр камеры 1 (и её рото), вставки и интро не поворачиваются; при зуме около 100% откроются углы — держи запас зума.",
                        "ctl": "num",
                        "min": -10,
                        "max": 10,
                        "lim_min": -45,
                        "lim_max": 45,
                        "step": 0.1,
                    },
                    {
                        "type": "field",
                        "key": "cam1_head_follow",
                        "label": "следить за головой",
                        "tip": "кадр камеры 1 едет за головой по горизонтали (по маске человека, как рото); считается на видеокарте при первой сборке и кэшируется рядом с XML; вставки кам1 и интро едут вместе с кадром.",
                        "ctl": "bool",
                    },
                    {
                        "type": "field",
                        "key": "cam1_head_x",
                        "label": "Голова по X, %",
                        "tip": None,
                        "ctl": "num",
                        "conv": "frac_pct",
                        "min": 0,
                        "max": 100,
                        "step": 0.5,
                        "show_if": {"key": "cam1_head_follow", "eq": True},
                    },
                    {
                        "type": "field",
                        "key": "cam1_head_smooth",
                        "label": "Плавность слежения, с",
                        "tip": None,
                        "ctl": "num",
                        "unit": "с",
                        "min": 0.1,
                        "max": 3.0,
                        "step": 0.1,
                        "show_if": {"key": "cam1_head_follow", "eq": True},
                    },
                    {
                        "type": "field",
                        "key": "cam1_head_min",
                        "label": "Следить от зума, %",
                        "tip": "слежение включается, только когда зум кадра (Scale нула Камеры 1) не меньше этого числа; ниже — кадр плавно возвращается на место. 0 — следить всегда. Порог — в тех же числах, что диапазоны скачков и наездов, без заполнения кадра.",
                        "ctl": "num",
                        "min": 0,
                        "max": 400,
                        "lim_min": 0,
                        "lim_max": 1000,
                        "step": 1,
                        "show_if": {"key": "cam1_head_follow", "eq": True},
                    },
                ],
            },
            {
                "type": "group",
                "id": "cam1.zoom",
                "label": "Анимация зума",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "cam1_zoom",
                        "label": "Зум кам1",
                        "tip": "Наезд с откатом: импульс 182→100% на каждом возврате с камеры 2. Резкие скачки: на каждом переключении кадра скейл мгновенно прыгает на случайные 100–140% (джамп-кат). Дрейф: скачок на случайные 100–160% в кате, затем плавный зум/анзум к новому числу к следующему кату — постоянное лёгкое движение. Нет зума: кадр неподвижен, скейл всегда 100%.",
                        "ctl": "select",
                        "options": [
                            ["pulse", "наезд с откатом (плавно)"],
                            ["jump", "резкие скачки 100–140%"],
                            ["drift", "дрейф 100–160% (плавный между катами)"],
                            ["none", "нет зума (кадр неподвижен)"],
                        ],
                    },
                    {
                        "type": "field",
                        "key": "cam1_zoom_start",
                        "label": "наезд в начале",
                        "tip": "Крупный наезд в первом кадре ролика. Снять — ролик начинается без наезда, возвраты с перебивок работают как обычно.",
                        "ctl": "bool",
                        "show_if": {"key": "cam1_zoom", "ne": "none"},
                    },
                    {
                        "type": "field",
                        "key": "cam1_zoom_big",
                        "label": "Первый наезд, %",
                        "tip": "Крупный наезд в первом кадре ролика: на сколько процентов кадр приближается (дефолт 182%). В резких скачках — плавный наезд от этого значения к первому скачку.",
                        "ctl": "num",
                        "show_if": {"key": "cam1_zoom", "in": ["pulse", "drift", "jump"]},
                        "min": 100,
                        "max": 300,
                        "lim_min": 100,
                        "lim_max": 400,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "cam1_zoom_lo",
                        "label": "Возвраты от, %",
                        "tip": "Возвраты с камеры 2: случайный пик в этом диапазоне (%), затем плавный откат в 100. Нижняя и верхняя границы. В «резких скачках» это же — границы случайного скачка. В «дрейфе» работают свои границы «Дрейф, диапазон %».",
                        "ctl": "num",
                        "show_if": {"key": "cam1_zoom", "in": ["pulse", "jump"]},
                        "min": 100,
                        "max": 250,
                        "lim_min": 10,
                        "lim_max": 400,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "cam1_zoom_hi",
                        "label": "Возвраты до, %",
                        "tip": "Возвраты с камеры 2: случайный пик в этом диапазоне (%), затем плавный откат в 100. Нижняя и верхняя границы. В «резких скачках» это же — границы случайного скачка. В «дрейфе» работают свои границы «Дрейф, диапазон %».",
                        "ctl": "num",
                        "show_if": {"key": "cam1_zoom", "in": ["pulse", "jump"]},
                        "min": 100,
                        "max": 250,
                        "lim_min": 10,
                        "lim_max": 400,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "cam1_take_zoom",
                        "label": "наезды в длинных тейках",
                        "tip": "В длинных тейках камера плавно подъезжает и отъезжает: один подъезд на +lo…+hi % от значения тейка, держит, затем отъезжает обратно. Если до ката мало места — остаётся приближенной до следующей склейки.",
                        "ctl": "bool",
                        "show_if": {"key": "cam1_zoom", "eq": "jump"},
                    },
                    {
                        "type": "field",
                        "key": "cam1_take_min",
                        "label": "Тейк длиннее, с",
                        "tip": "Минимальная длительность тейка (в секундах), в котором делается плавный наезд камеры.",
                        "ctl": "num",
                        "show_if": {"key": "cam1_zoom", "eq": "jump"},
                        "min": 3,
                        "max": 60,
                        "lim_min": 3,
                        "lim_max": 60,
                        "step": 0.5,
                    },
                    {
                        "type": "field",
                        "key": "cam1_take_lo",
                        "label": "Наезд от, %",
                        "tip": "Нижняя граница наезда в тейке: на сколько процентов увеличивается масштаб камеры (от значения тейка).",
                        "ctl": "num",
                        "show_if": {"key": "cam1_zoom", "eq": "jump"},
                        "min": 5,
                        "max": 100,
                        "lim_min": 5,
                        "lim_max": 100,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "cam1_take_hi",
                        "label": "Наезд до, %",
                        "tip": "Верхняя граница наезда в тейке: на сколько процентов увеличивается масштаб камеры (от значения тейка).",
                        "ctl": "num",
                        "show_if": {"key": "cam1_zoom", "eq": "jump"},
                        "min": 5,
                        "max": 100,
                        "lim_min": 5,
                        "lim_max": 100,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "cam1_take_hold",
                        "label": "Держать наезд, с",
                        "tip": "Сколько секунд камера держит приближенный масштаб перед отъездом обратно.",
                        "ctl": "num",
                        "show_if": {"key": "cam1_zoom", "eq": "jump"},
                        "min": 0.5,
                        "max": 10,
                        "lim_min": 0.5,
                        "lim_max": 10,
                        "step": 0.1,
                    },
                    {
                        "type": "field",
                        "key": "cam1_take_yellow",
                        "label": "наезд на жёлтых словах",
                        "tip": "в длинном тейке подъезд приходит ровно на первое жёлтое слово; тейк без жёлтых — как обычно",
                        "ctl": "bool",
                        "show_if": {"key": "cam1_zoom", "eq": "jump"},
                    },
                    {
                        "type": "field",
                        "key": "cam1_drift_lo",
                        "label": "Дрейф от, %",
                        "tip": "Границы случайного масштаба при дрейфе: нижняя и верхняя, %. В кате масштаб прыгает на случайное число в этом интервале, затем плавно дрейфует к следующему.",
                        "ctl": "num",
                        "show_if": {"key": "cam1_zoom", "eq": "drift"},
                        "min": 50,
                        "max": 250,
                        "lim_min": 10,
                        "lim_max": 400,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "cam1_drift_hi",
                        "label": "Дрейф до, %",
                        "tip": "Границы случайного масштаба при дрейфе: нижняя и верхняя, %. В кате масштаб прыгает на случайное число в этом интервале, затем плавно дрейфует к следующему.",
                        "ctl": "num",
                        "show_if": {"key": "cam1_zoom", "eq": "drift"},
                        "min": 50,
                        "max": 250,
                        "lim_min": 10,
                        "lim_max": 400,
                        "step": 1,
                    },
                ],
            },
            {
                # Цвет камер через Lumetri (задание ZJ): группа-галка, как «Фон субтитров».
                # Значения — ровно те же ползунки, что в панели Lumetri в AE; сборка кладёт
                # один эффект ADBE Lumetri на клипы камер и их рото-копии (xml2ae/build.py),
                # превью показывает приближение тем же числом.
                "type": "group",
                "id": "cam1.lm",
                "label": "Цвет (Lumetri)",
                "fx": True,
                "toggle": "lm_on",
                "tip": "Lumetri Color на все клипы камер и их рото-копии; экспозиция клипа (шаг AE) прибавляется к этой. В превью — приближённо",
                "items": [
                    {
                        "type": "field",
                        "key": "lm_exposure",
                        "label": "Экспозиция",
                        "tip": None,
                        "ctl": "num",
                        "min": -5,
                        "max": 5,
                        "step": 0.05,
                    },
                    {
                        "type": "field",
                        "key": "lm_contrast",
                        "label": "Контраст",
                        "tip": None,
                        "ctl": "num",
                        "min": -100,
                        "max": 100,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "lm_highlights",
                        "label": "Светлые (Highlights)",
                        "tip": None,
                        "ctl": "num",
                        "min": -100,
                        "max": 100,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "lm_shadows",
                        "label": "Тени (Shadows)",
                        "tip": None,
                        "ctl": "num",
                        "min": -100,
                        "max": 100,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "lm_whites",
                        "label": "Белые (Whites)",
                        "tip": None,
                        "ctl": "num",
                        "min": -100,
                        "max": 100,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "lm_blacks",
                        "label": "Тёмные (Blacks)",
                        "tip": None,
                        "ctl": "num",
                        "min": -100,
                        "max": 100,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "lm_temp",
                        "label": "Температура",
                        "tip": None,
                        "ctl": "num",
                        "min": -100,
                        "max": 100,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "lm_tint",
                        "label": "Оттенок (Tint)",
                        "tip": None,
                        "ctl": "num",
                        "min": -100,
                        "max": 100,
                        "step": 1,
                    },
                    {
                        "type": "field",
                        "key": "lm_sat",
                        "label": "Насыщенность",
                        "tip": None,
                        "ctl": "num",
                        "min": 0,
                        "max": 200,
                        "step": 1,
                    },
                ],
            },
        ],
    },
    {
        "id": "inserts",
        "label": "Вставки",
        "toggle": None,
        "items": [
            {
                "type": "group",
                "id": "inserts.photo",
                "label": "Фото",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "insert_style",
                        "label": "Стиль фотовставок",
                        "tip": None,
                        "ctl": "select",
                        "options": [
                            ["auto", "авто"],
                            ["cam1", "Кам 1 (из-за спины)"],
                            ["cam2", "Кам 2 (наезд+блюр)"],
                        ],
                    },
                    {
                        "type": "field",
                        "key": "insert_anim",
                        "label": "Анимация фото",
                        "tip": "Как фото-вставка появляется и уходит: наезд от большего с блюром (как сегодня), выезд снизу с ростом и фейдом (субтитры на время вставки уходят) или без анимации — фото просто появляется и исчезает (для роликов с одной камерой).",
                        "ctl": "select",
                        "options": [
                            ["zoom", "наезд + блюр"],
                            ["rise", "выезд снизу + фейд"],
                            ["none", "без анимации"],
                        ],
                    },
                    {
                        "type": "field",
                        "key": "insert_fx",
                        "label": "Эффекты фото",
                        "tip": "Новые: чёрная тень 49% (135°, 15px, софт 70) + маска-скругление на прекомпе. Старые: белый Drop Shadow + Simple Choker. Без эффекта: фото без тени, маски и чокера — для роликов с одной камерой.",
                        "ctl": "select",
                        "options": [
                            ["card", "новые (чёрная тень + скругление)"],
                            ["white", "старые (белая тень + чокер)"],
                            ["none", "без эффекта"],
                        ],
                    },
                    {
                        "type": "field",
                        "key": "insert_snap_cut",
                        "label": "Обрезать фото на смене камеры",
                        "tip": "Фото-вставку (b-roll над головой), которая переходит на другую камеру (кам1↔кам2), обрезаем ровно в точке смены ракурса, без анимации исчезновения. Фото внутри одной камеры доигрывают выход. ВИДЕО не режется никогда — играет весь свой хрон.",
                        "ctl": "bool",
                    },
                    {
                        "type": "field",
                        "key": "insert_plate_file",
                        "label": "Подложка (файл)",
                        "tip": "картинка-подложка для вставок с галкой «на подложке»; у остальных вставок её нет",
                        "ctl": "file",
                        "nullable": True,
                    },
                    {
                        "type": "field",
                        "key": "insert_plate_scale",
                        "label": "Масштаб подложки, %",
                        "tip": "масштаб картинки-подложки, % (30-300). Вставку и её фото не трогает: у вставок без галки «на подложке» подложки нет вовсе",
                        "ctl": "num",
                        "min": 30,
                        "max": 300,
                        "lim_min": 10,
                        "lim_max": 500,
                        "step": 1,
                    },
                ],
            },
            {
                "type": "group",
                "id": "inserts.tr",
                "label": "Transform",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "insert_c2_x",
                        "label": "Вставки кам2 X, %",
                        "tip": "Точка покоя вставок Кам2 (% ширины и высоты кадра, дефолт X 50% / Y 17.2%). В AE правилось руками в каждом ролике — здесь это стиль спикера.",
                        "ctl": "num",
                        "conv": "frac_pct",
                        "min": 0,
                        "max": 100,
                        "step": 0.5,
                    },
                    {
                        "type": "field",
                        "key": "insert_c2_y",
                        "label": "Вставки кам2 Y, %",
                        "tip": "Точка покоя вставок Кам2 (% ширины и высоты кадра, дефолт X 50% / Y 17.2%). В AE правилось руками в каждом ролике — здесь это стиль спикера.",
                        "ctl": "num",
                        "conv": "frac_pct",
                        "min": 0,
                        "max": 100,
                        "step": 0.1,
                    },
                    {
                        "type": "field",
                        "key": "insert_c1_x",
                        "label": "Вставки кам1 X, %",
                        "tip": "Общий сдвиг точки покоя вставок Кам1 (% ширины и высоты кадра). Вставка кам1 в кадре Камеры 1 наследует зум нула камеры, поэтому и сдвиг масштабируется. В стиле хранится в px.",
                        "ctl": "num",
                        "conv": "pct_fx",
                        "min": -50,
                        "max": 50,
                        "step": 0.5,
                    },
                    {
                        "type": "field",
                        "key": "insert_c1_y",
                        "label": "Вставки кам1 Y, %",
                        "tip": "Общий сдвиг точки покоя вставок Кам1 (% ширины и высоты кадра). Вставка кам1 в кадре Камеры 1 наследует зум нула камеры, поэтому и сдвиг масштабируется. В стиле хранится в px.",
                        "ctl": "num",
                        "conv": "pct_fy",
                        "min": -50,
                        "max": 50,
                        "step": 0.5,
                    },
                    {
                        "type": "field",
                        "key": "insert_c1on2_x",
                        "label": "Вылет на перебивке X, %",
                        "tip": "Стиль «Кам 1» задан на весь ролик, а вставка попала на перебивку Камеры 2: сдвиг точки покоя (% ширины и высоты кадра). В стиле хранится в px.",
                        "ctl": "num",
                        "conv": "pct_fx",
                        "show_if": {"key": "insert_style", "eq": "cam1"},
                        "min": -50,
                        "max": 50,
                        "step": 0.5,
                    },
                    {
                        "type": "field",
                        "key": "insert_c1on2_y",
                        "label": "Вылет на перебивке Y, %",
                        "tip": "Стиль «Кам 1» задан на весь ролик, а вставка попала на перебивку Камеры 2: сдвиг точки покоя (% ширины и высоты кадра). В стиле хранится в px.",
                        "ctl": "num",
                        "conv": "pct_fy",
                        "show_if": {"key": "insert_style", "eq": "cam1"},
                        "min": -50,
                        "max": 50,
                        "step": 0.5,
                    },
                ],
            },
            {
                "type": "group",
                "id": "inserts.video",
                "label": "Видео",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "transition",
                        "label": "Видео-переход",
                        "tip": "Обрезка перехода, точка удара и громкость: открыть редактор.",
                        "ctl": "file",
                        "sfx": "transition",
                        "video": True,
                        "nullable": True,
                        "placeholder": "Quick 2.mov",
                    },
                ],
            },
        ],
    },
    {
        "id": "roto",
        "label": "Рото",
        "toggle": "roto",
        "items": [
            {
                "type": "field",
                "key": "roto_bottom",
                "label": "Низ маски, %",
                "tip": None,
                "ctl": "num",
                "min": 0,
                "max": 100,
                "step": 1,
                "conv": "frac_pct_int",
                "hint": "rotomask",
            },
            {
                "type": "field",
                "key": "roto_device",
                "label": "Устройство рото",
                "tip": None,
                "ctl": "select",
                "nullable": True,
                "options": [
                    ["", "авто"],
                    ["cuda", "GPU"],
                    ["cpu", "CPU"],
                ],
            },
            {
                "type": "field",
                "key": "roto_cam1_only",
                "label": "Рото только на Камере 1",
                "tip": "Ротоскоп делается только на кусках, где в кадре Камера 1. На перебивках Камеры 2 рото не строится (быстрее и без артефактов на широком плане).",
                "ctl": "bool",
            },
        ],
    },
    {
        "id": "audio",
        "label": "Аудио",
        "toggle": None,
        "items": [
            {
                "type": "group",
                "id": "audio.voice",
                "label": "Голос",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "voice_db",
                        "label": "Голос, dB",
                        "tip": "Базовая громкость голоса (камера 1). Цензура ныряет отсюда в −100 и обратно.",
                        "ctl": "num",
                        "min": -40,
                        "max": 6,
                        "step": 0.5,
                    },
                    {
                        "type": "field",
                        "key": "audio_fades",
                        "label": "Микро-фейды на склейках звука",
                        "tip": "Микро-фейд ~10мс на краях аудио-клипов камеры — убирает щелчки на склейках. Снять — звук режется жёстко.",
                        "ctl": "bool",
                    },
                ],
            },
            {
                "type": "group",
                "id": "audio.music",
                "label": "Музыка",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "music_db",
                        "label": "Музыка тише, dB",
                        "tip": None,
                        "ctl": "num",
                        "min": -40,
                        "max": 6,
                        "step": 0.5,
                    },
                ],
            },
            {
                "type": "group",
                "id": "audio.pop",
                "label": "Поп",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "pop",
                        "label": "Звук «поп» на жёлтые",
                        "tip": "Обрезка «попа», точка удара и громкость: открыть редактор звука.",
                        "ctl": "file",
                        "sfx": "pop",
                        "nullable": True,
                        "placeholder": "highlight_pop",
                    },
                    {
                        "type": "field",
                        "key": "pop_db",
                        "label": "Поп, dB",
                        "tip": "Смещение громкости от базовых −8 dB встроенного звука «поп».",
                        "ctl": "num",
                        "min": -40,
                        "max": 6,
                        "step": 0.5,
                    },
                    {
                        "type": "field",
                        "key": "pop_lead",
                        "label": "Поп позже на, кадр.",
                        "tip": "На сколько кадров «поп» ставится ПОЗЖЕ жёлтого. Удар (at) — свойство файла, это — вкус: чуть позже ложится лучше.",
                        "ctl": "int",
                        "positive": True,
                        "min": 0,
                        "max": 30,
                        "lim_min": 0,
                        "lim_max": 60,
                    },
                ],
            },
            {
                "type": "group",
                "id": "audio.whoosh",
                "label": "Whoosh",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "transition_sfx",
                        "label": "Звук перехода",
                        "tip": "Обрезка whoosh, точка удара и громкость: открыть редактор звука.",
                        "ctl": "file",
                        "sfx": "transition_sfx",
                        "nullable": True,
                        "placeholder": "whoosh",
                    },
                ],
            },
            {
                "type": "group",
                "id": "audio.riser",
                "label": "Интро SFX",
                "fx": False,
                "toggle": "intro_riser",
                "items": [
                    {
                        "type": "field",
                        "key": "intro_riser_file",
                        "label": "Ризер (файл)",
                        "tip": "Обрезка ризера, точка удара и громкость: открыть редактор звука.",
                        "ctl": "file",
                        "sfx": "intro_riser",
                        "nullable": True,
                        "placeholder": "ассет по умолчанию",
                    },
                ],
            },
            {
                "type": "group",
                "id": "audio.glitch",
                "label": "Глитч",
                "fx": False,
                "toggle": None,
                "items": [
                    {
                        "type": "field",
                        "key": "glitch",
                        "label": "Звук глитча интро",
                        "tip": "Обрезка глитча, точка удара и громкость: открыть редактор звука.",
                        "ctl": "file",
                        "sfx": "glitch",
                        "nullable": True,
                        "placeholder": "gltchgltch_24.wav",
                    },
                    {
                        "type": "field",
                        "key": "glitch_db",
                        "label": "Глитч, dB",
                        "tip": "Громкость звука глитча интро (0 dB = как в файле).",
                        "ctl": "num",
                        "min": -40,
                        "max": 6,
                        "step": 0.5,
                    },
                ],
            },
        ],
    },
]

EXTERNAL = {
    "label": "имя шаблона",
    "intro_mode": "пишется из переключателя клипа #intromode в редакторе слов",
}


def schema():
    """Возвращает схему панели стиля, базовые значения BASE и внешние ключи."""
    return {
        "layers": LAYERS,
        "base": copy.deepcopy(styles.BASE),
        "external": sorted(EXTERNAL),
    }
